---
name: Test-Mock-Class
version: 0.0303
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
abstract: Simulating other classes
license: lgpl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-Mock-Class
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
  repository: http://github.com/dex4er/Test-Mock-Class
build_requires:
  Class::Inspector: 0
  Test::Unit::Lite: 0.12
requires:
  Class::MOP: 0.93
  Exception::Base: 0
  Exception::Fatal: 0
  Moose: 0.9
  Test::Assert: 0.05
  namespace::clean: 0
  perl: 5.006
provides:
  Test::Mock::Class:
    file: lib/Test/Mock/Class.pm
    version: 0.0303
  Test::Mock::Class::Role::Meta::Class:
    file: lib/Test/Mock/Class/Role/Meta/Class.pm
    version: 0.0303
  Test::Mock::Class::Role::Object:
    file: lib/Test/Mock/Class/Role/Object.pm
    version: 0.0303
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
